apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: cert-manager
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: 1.2.0
  values:
    installCRDs: false
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: <<add arn of the role with Route53 access>>
    securityContext:
      enabled: true
      fsGroup: 1001
